
# Example file for setting up exercises.

# The app name appears at the top of your exercise set.
app_name : 'Nutmeg'

# Theme name.
theme: 'default'
# Path to the theme files, relative to the the project root.
theme_path: 'themes'

# Contexts determine what gets rendered.
contexts :
  # Machine name of the context.
  home :
    # Human readable name
    name : 'Home'
    # Handling class.
    handler : '\Nutmeg\Context\Home'
  exercise:
    name: 'Exercises'
    handler : '\Nutmeg\Context\Exercise'

# Each exercise should be documented here.
exercises :
  # The key is the unique machine name.
  1 :
    # Human readable name.
    name : 'Sample exercise 1'
    # ExerciseFileLoader to load.
    file : 'index.php'
  2 :
    name : 'Sample exercise 2'
    file : 'index.php'